sudo: required
services:
  - docker

before_install:
  - docker build -t logan99/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true logan99/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "My-Docker-app"
  env: "My-Docker-App-env"
  bucket_name: "elasticbeanstalk-us-east-1-116057137175"
  bucket_path: "My-Docker-app"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"